"""add guest to Role

Revision ID: 664e3a205f5f
Revises: 6f1d64fe1eaf
Create Date: 2025-01-28 13:37:37.149573

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa  # noqa: F401
import sqlmodel  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = "664e3a205f5f"
down_revision: Union[str, None] = "6f1d64fe1eaf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the new "guest" value to the existing ENUM type
    op.execute("ALTER TYPE role ADD VALUE 'guest'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

    # Remove the 'guest' value from the enum
    # First, update any rows with 'guest' to a valid value
    op.execute("UPDATE \"user\" SET role = 'user' WHERE role = 'guest'")

    # Drop the 'guest' value (PostgreSQL doesn't allow dropping enum values directly, 
    # so we may need to create a new enum without the value and migrate the column)
    op.execute("CREATE TYPE role_temp AS ENUM ('admin', 'user')")
    op.execute("ALTER TABLE \"user\" ALTER COLUMN role TYPE role_temp USING role::text::role_temp")
    op.execute("DROP TYPE role")
    op.execute("ALTER TYPE role_temp RENAME TO role")