"""change float to decimal on prices

Revision ID: 70e914584824
Revises: ebca1aa5bd57
Create Date: 2025-02-19 09:44:49.012822

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "70e914584824"
down_revision: Union[str, None] = "ebca1aa5bd57"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "auction",
        "starting_price",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "auction",
        "min_bid",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "auction",
        "instant_buy_price",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "auction",
        "sold_price",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(scale=2),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "auction",
        "sold_price",
        existing_type=sa.Numeric(scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "auction",
        "instant_buy_price",
        existing_type=sa.Numeric(scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "auction",
        "min_bid",
        existing_type=sa.Numeric(scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "auction",
        "starting_price",
        existing_type=sa.Numeric(scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
