"""move sold from auction to product

Revision ID: 75a1c9716401
Revises: 70e914584824
Create Date: 2025-02-19 10:11:42.190161

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "75a1c9716401"
down_revision: Union[str, None] = "70e914584824"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1️⃣ Add column with `nullable=True` first
    op.add_column("product", sa.Column("sold", sa.Boolean(), nullable=True))

    # 2️⃣ Update `sold` values correctly
    op.execute(
        """
        UPDATE product
        SET sold = COALESCE(
            (SELECT BOOL_OR(auction.sold) FROM auction WHERE auction.product_id = product.id),
            FALSE  -- Default value if no auction exists
        )
        """
    )

    # 3️⃣ Now make `sold` NOT NULL
    op.alter_column("product", "sold", nullable=False)

    # 4️⃣ Drop `sold` column from `auction`
    op.drop_column("auction", "sold")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product", "sold")
    op.add_column(
        "auction",
        sa.Column("sold", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
