"""add 'instant_buy' bool to auction

Revision ID: ae6ab3624587
Revises: 75a1c9716401
Create Date: 2025-02-24 10:47:35.364405

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ae6ab3624587"
down_revision: Union[str, None] = "75a1c9716401"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1️⃣ Add column with `nullable=True` first
    op.add_column(
        "auction", sa.Column("instant_buy", sa.Boolean(), nullable=True)
    )

    # 2️⃣ Set all existing auctions to `False`
    op.execute(
        """
        UPDATE auction
        SET instant_buy = FALSE
        WHERE instant_buy IS NULL
        """
    )

    # 3️⃣ Now make `instant_buy` NOT NULL
    op.alter_column("auction", "instant_buy", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column("auction", "instant_buy")
    # ### end Alembic commands ###
